#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-scalatest_2.11
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0-sources.jar
Source0  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0-sources.jar
Source1  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.jar
Source2  : https://repo.maven.apache.org/maven2/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-scalatest_2.11-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-scalatest_2.11 package.
Group: Data

%description data
data components for the mvn-scalatest_2.11 package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0-sources.jar
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.jar
/usr/share/java/.m2/repository/org/scalatest/scalatest_2.11/3.0.0/scalatest_2.11-3.0.0.pom
